### ISSUE TITLE
Missing field in DetailedActivity

### ISSUE THREAD

**Issue by maksim77** [rfoel/strava#61]
Hi!
First of all, thank you so much for the library!

Unfortunately, there is an inaccuracy in the Strava documentation. The `getActivityById` method returns a json containing fields that are not present in the object description in the documentation. This can be easily detected by simply looking at the example that the authors themselves give on the right side of the documentation [page](https://developers.strava.com/docs/reference/#api-Activities-getActivityById).
In particular I am interested in two fields currently missing from your implementation:

1. average_cadence
1. suffer_score

**Comment by maksim77** [comment]
After I wrote the issue, I saw that you recently already added this #58.
I understand correctly that the problem is only in the version that is in the npm registry and that I use in the project?
Sorry for the stupid question :). js is not my native language :)

**Comment by rfoel** [comment]
@maksim77 Someone added them and I released the version 1.3.1 with them, 20 days ago. JS is no one native language, unless you're a bot haha

**Comment by maksim77** [comment]
In 1.3.1 your add this fields in Summary Activity. But this fields still missing in DetailActivity :(
